### ISSUE TITLE
Scripts not permitted to use new io.fabric8.openshift.client.DefaultOpenShiftClient

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/jenkins-docker#129]
Hi,
Since last week our jenkins jobs fails. We are not running the latest version of anything. The version of jenkins is 2.19.1.
The error is:
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new io.fabric8.openshift.client.DefaultOpenShiftClient

Is it possible for me to somewhere specify to use an older version of jenkins-docker?
Is it possible for me to migrate my jenkins-docker to the latest version without reinstalling fabric8?

Thanks,
Christer

**Comment by rawlingsj** [comment]
Can you gist your Jenkinsfile please?  I wonder if you have an old one that doesn't include a version in the `@Library` annotation.  The tag version should match your jenkins-docker image tag version.

i.e. 
```
@Library('github.com/fabric8io/fabric8-pipeline-library@v2.2.311')
```

**Comment by chbe8475** [comment]
Jenkinsfile:
`#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')

def failIfNoTests = ""
try {
  failIfNoTests = ITEST_FAIL_IF_NO_TEST
} catch (Throwable e) {
  failIfNoTests = "false"
}

def localItestPattern = ""
try {
  localItestPattern = ITEST_PATTERN
} catch (Throwable e) {
  localItestPattern = "*KT"
}


def versionPrefix = ""
try {
  versionPrefix = VERSION_PREFIX
} catch (Throwable e) {
  versionPrefix = "1.0"
}

def canaryVersion = "${versionPrefix}.${env.BUILD_NUMBER}"
def utils = new io.fabric8.Utils()
def label = "buildpod.${env.JOB_NAME}.${env.BUILD_NUMBER}".replace('-', '_').replace('/', '_')

podTemplate(label: label, serviceAccount: 'jenkins', containers: [
        [name: 'maven', image: 'fabric8/maven-builder', command: 'cat', ttyEnabled: true, envVars: [
                [key: 'MAVEN_OPTS', value: '-Duser.home=/home/jenkins/'],
                [key: 'DOCKER_CONFIG', value: '/home/jenkins/.docker/'],
                [key: 'KUBERNETES_MASTER', value: 'kubernetes.default']]],
        [name: 'jnlp', image: 'iocanel/jenkins-jnlp-client:latest', command:'/usr/local/bin/start.sh', args: '${computer.jnlpmac} ${computer.name}', ttyEnabled: false,
                envVars: [[key: 'DOCKER_HOST', value: 'unix:/var/run/docker.sock']]]],
        volumes: [
                [$class: 'PersistentVolumeClaim', mountPath: '/home/jenkins/.mvnrepository', claimName: 'jenkins-mvn-local-repo'],
                [$class: 'SecretVolume', mountPath: '/home/jenkins/.m2/', secretName: 'jenkins-maven-settings'],
                [$class: 'SecretVolume', mountPath: '/home/jenkins/.docker', secretName: 'jenkins-docker-cfg'],
                [$class: 'HostPathVolume', mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock']
        ]) {
  node(label) {
  def envStage = utils.environmentNamespace('staging')
    git 'http://gogs.default.mypages.prv.se/gogsadmin/stage-samlauthserver.git'

    echo 'NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node'
    container(name: 'maven') {

      stage 'Build Release'
      mavenCanaryRelease {
        version = canaryVersion
      }

      stage 'Integration Test'
      mavenIntegrationTest {
        environment = 'Testing'
        failIfNoTests = localFailIfNoTests
        itestPattern = localItestPattern
      }

    stage 'Rollout Staging'
    kubernetesApply(environment: envStage)
    }
  }
}`

When I change to version v2.2.311 I get this error:
ERROR: No version v2.2.311 found for library github.com/fabric8io/fabric8-pipeline-library

**Comment by chbe8475** [comment]
Gist:
https://gist.github.com/chbe8475/0d86a1733053d0209dea1abd84064b44

**Comment by rawlingsj** [comment]
What version of jenkins do you have running?  It sounds like its an old one, I think there was an issue with the jenkins plugin not working with tags that's why the Jenkinsfiles weren't versioned for a while.  If we can get the jenkins-docker image version then I can fork the library from an old commit that ties up to that version and you can try that instead.
Openshift
```
oc get dc jenkins -o yaml | grep 'image:'
```
Kubernetes
```
oc get deployment jenkins -o yaml | grep 'image:'
```

**Comment by chbe8475** [comment]
Yes, it is old :-)

kubectl get deployment jenkins -o yaml | grep 'image:'
        image: fabric8/jenkins-docker:2.2.297

**Comment by rawlingsj** [comment]
OK that's good.  I've just created a new repo and reset to a commit around the same time as the 2.2.297 release was cut.  Fingers crossed this works.  Can you please try and change `@Library` in your Jenkinsfile to:

```
@Library('github.com/fabric8io/fabric8-pipeline-library-pre-versioning@master')
```

**Comment by chbe8475** [comment]
That on works. Great. but how do I solve this in a permanent fashion? Is it possible to change to a later version of fabric8/jenkins-docker within this fabric8 installation that I am using?
