### ISSUE TITLE
PR #1 for jenkins-docker

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/jenkins-docker#2]
hey, so i've got a PR to update the jenkins-docker image to add a conditional-buildstep plugin (i may have commit rights to this, but wanted to make the PR explicit to chat about it really quick... when i try to run docker build for this image, i get issues with rpm repos, etc. how do we generate a new image of this that can get into docker hub?

**Comment by jimmidyson** [comment]
This should be an automated build on docker hub but it seems to have the same problem as you do with the yum repos. I'll take a look tomorrow if that's alright - unless this is crazy urgent for you?

**Comment by christian-posta** [comment]
@jimmidyson nah, not crazy urgent at the moment, so thanks. can work around it; trying to tackle bigger fish. even if this does get in there, the jenkins job dsl seems to have some issue with creating conditional post-build steps: https://groups.google.com/forum/#!topic/job-dsl-plugin/iGsDyivxRdE

**Comment by christian-posta** [comment]
@jimmidyson oddly enough, this started to work on my box.. crossing fingers.. have another PR and hopefully docker hub can run the build. is there a place that shows the status of those builds on docker hub?

**Comment by jstrachan** [comment]
@christian-posta you can see the status of builds and logs here: https://registry.hub.docker.com/u/fabric8/jenkins/builds_history/187237/

grab me on IRC for the login/pwd. Looks like its currently failing installing openjdk 1.7.0 :(. Lemme trigger another build just in case

**Comment by christian-posta** [comment]
@jstrachan Did it go again? Looks like it passed?

byxt7fpyekmrk7djabygrgy	Finished	2015-06-18 22:38:53	2015-06-18 22:48:14

There was some wonkiness with installing JDK on my side too.. but it did finally succeed (w/out any changes to Dockerfile).

**Comment by jstrachan** [comment]
worked this time!

**Comment by jimmidyson** [comment]
Looked like a temp problem with the centos yum repos. Not much we can do about that but set up notifications of failures if possible.
