### ISSUE TITLE
Idea: Replace interpolate_env() with gettext-base

### ISSUE THREAD

**Issue by hacfi** [fabric8io/jenkins-docker#48]
This repository helped me a lot setting up a custom Docker image for jenkins...thanks!

Just to let you know: instead of the custom `interpolate_env()` function you could install the debian package `gettext-base` and run:
`envsubst < /var/jenkins_home/config.xml > /var/jenkins_home/config.xml`
(not 100% sure that you can write to the same file - if not just name one `config.xml.template`)

The only feature you lose is the output of the substitutions made.

**Comment by iocanel** [comment]
@hacfi: Thanks for the feedback and the suggestion. Did you have any kind of issues with the interpolate_env() and searched for alternatives, or you just preferred something that is more thoroughly tested?

**Comment by hacfi** [comment]
@iocanel It was just a hint "hey, there is a tool for it" - I didn’t have any issues with it. Two hours after I created this issue I ran into an issue with `envsubst` though: when having `$` in the files it always replaces them so things like `<authorizationStrategy class="hudson.security.AuthorizationStrategy$Unsecured"/>` (https://github.com/fabric8io/jenkins-docker/blob/master/config/config.xml#L8) will be changed to `<authorizationStrategy class="hudson.security.AuthorizationStrategy"/>`. Closing this ticket and I will actually take the `interpolate_env` :)
